### ISSUE TITLE
sw_measurement not working

### ISSUE THREAD

**Issue by MYasirSheikh** [sitewhere/sitewhere-arduino#2]
I have an ESP8266 set up with SiteWhere. Everything's working fine except the function for sending device measurements. sw_alert, sw_location have been tested to work. only the measure tab does not receive anything with sw_measurement function. Here's the code snippet
`if (len = sw_acknowledge(hardwareId, "Command Received", buffer, sizeof(buffer), originator)) {
      my_mqttclient.publish(outbound, buffer, len);
    }
    if (len = sw_measurement(hardwareId, "engine.temp", 25.1, NULL, buffer, sizeof(buffer), originator)) {
      Serial.println("sending measurements");
      my_mqttclient.publish(outbound, buffer, len);
    }
    if (len = sw_alert(hardwareId, "voltage", "myString", NULL, buffer, sizeof(buffer), originator)) {
      Serial.println("sending alert");
      my_mqttclient.publish(outbound, buffer, len);
    }`
Ack, and alerts work fine, but measurement part does not though the "if" condition goes true for measurement.

**Comment by MYasirSheikh** [comment]
Also the latest commit shows compile errors for handling custom commands. It takes ENUM, STRING and other fields defined by SiteWhere to be undeclared. Need some help here!!
Thanks

**Comment by derekadams** [comment]
Some of the examples (including the one for custom commands) have not been updated to use the latest libraries. As soon as we have the time, we will update the others. Also, we have had another report of problems with the `sw_measurement` function and will take a look.

**Comment by MYasirSheikh** [comment]
Thanks for the quick response. Just found a fix for it. The latest commit uses PBFIELD instead of PBFIELD2 to define the the fields for custom commands in "custom.c" file in the example "CustomCommands".
Closing the issue :)
